### ISSUE TITLE
이미지 관리 방식

### ISSUE THREAD

**Issue by asdfg5415** [ssu-capstone2-DeunDeun/DeunDeun-backend#50]
## 문제
`Clubrecruit` `Post` 는 본문에 이미지를 포함하고 있다. 
이런 경우, 어차피 통째로 저장하기 때문에, `List<String> images`로 관리하는게 무의미하다.
왜냐하면, 본문에 이미 url을 포함하고 있기 때문이다.

이걸 따로 DB에 개별로 저장해둬서 의미가 있는지도 잘 모르겠다. 
단순히 영속성을 제공하는 정도? `OR` 단지 어떤 게시물에 어떤 이미지가 있구나 정도?
즉, 다시 해당 게시물을 조회해서 리턴하는 작업에서는 `List<String> imageUrls`를  순회할 필요가 없다.

또한,
게시물을 수정하는 경우, 
`content`의 update  쿼리 + 해당 이미지를 url을 DB상에서 DELETE 거는 작업까지 추가적으로 이루어져야한다.

하지만, 단순히 본문에 url을 포함시켜 `content`만으로 저장하는 경우에는 `content`의 update만 하면 된다.

## 해결

`ClubRecruit`와 `Post`의 이미지들은 content에 포함시키는 방식으로 도메인 구조를 변경한다.

**Comment by ghost** [comment]
수정해서 이슈 닫겠습니다.
